package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ColumnBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.COLUMN_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.COLUMN_NAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.ORDER_NUM
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.WIDTH
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.ISSHOW
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.SORT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.ISCANSORT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal iscansort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_COLUMN.DATAPROPERTYNAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String datapropertyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.COLUMN_ID
     *
     * @return the value of F_COLUMN.COLUMN_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.COLUMN_ID
     *
     * @param columnId the value for F_COLUMN.COLUMN_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.COLUMN_NAME
     *
     * @return the value of F_COLUMN.COLUMN_NAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.COLUMN_NAME
     *
     * @param columnName the value for F_COLUMN.COLUMN_NAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.ORDER_NUM
     *
     * @return the value of F_COLUMN.ORDER_NUM
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.ORDER_NUM
     *
     * @param orderNum the value for F_COLUMN.ORDER_NUM
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setOrderNum(BigDecimal orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.WIDTH
     *
     * @return the value of F_COLUMN.WIDTH
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.WIDTH
     *
     * @param width the value for F_COLUMN.WIDTH
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.ISSHOW
     *
     * @return the value of F_COLUMN.ISSHOW
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.ISSHOW
     *
     * @param isshow the value for F_COLUMN.ISSHOW
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIsshow(BigDecimal isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.SORT
     *
     * @return the value of F_COLUMN.SORT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.SORT
     *
     * @param sort the value for F_COLUMN.SORT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.ISCANSORT
     *
     * @return the value of F_COLUMN.ISCANSORT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIscansort() {
        return iscansort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.ISCANSORT
     *
     * @param iscansort the value for F_COLUMN.ISCANSORT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIscansort(BigDecimal iscansort) {
        this.iscansort = iscansort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.ISDELETE
     *
     * @return the value of F_COLUMN.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.ISDELETE
     *
     * @param isdelete the value for F_COLUMN.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.CREATEAT
     *
     * @return the value of F_COLUMN.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.CREATEAT
     *
     * @param createat the value for F_COLUMN.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.CREATEBY
     *
     * @return the value of F_COLUMN.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.CREATEBY
     *
     * @param createby the value for F_COLUMN.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.UPDATEAT
     *
     * @return the value of F_COLUMN.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.UPDATEAT
     *
     * @param updateat the value for F_COLUMN.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.UPDATEBY
     *
     * @return the value of F_COLUMN.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.UPDATEBY
     *
     * @param updateby the value for F_COLUMN.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_COLUMN.DATAPROPERTYNAME
     *
     * @return the value of F_COLUMN.DATAPROPERTYNAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getDatapropertyname() {
        return datapropertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_COLUMN.DATAPROPERTYNAME
     *
     * @param datapropertyname the value for F_COLUMN.DATAPROPERTYNAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setDatapropertyname(String datapropertyname) {
        this.datapropertyname = datapropertyname == null ? null : datapropertyname.trim();
    }
}