package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FileBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.FILE_ID
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.ORIGINALNAME
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String originalname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.SUFFIX
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.FILESIZE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private BigDecimal filesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.MD5
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.FK_VALUELIST_KEY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String fkValuelistKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.SERVERSIDEPATH
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String serversidepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.UPLOADINGUSER
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String uploadinguser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.NOTE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.ISDELETE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.CREATEAT
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.CREATEBY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.UPDATEAT
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_FILE.UPDATEBY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.FILE_ID
     *
     * @return the value of F_FILE.FILE_ID
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.FILE_ID
     *
     * @param fileId the value for F_FILE.FILE_ID
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.ORIGINALNAME
     *
     * @return the value of F_FILE.ORIGINALNAME
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getOriginalname() {
        return originalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.ORIGINALNAME
     *
     * @param originalname the value for F_FILE.ORIGINALNAME
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setOriginalname(String originalname) {
        this.originalname = originalname == null ? null : originalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.SUFFIX
     *
     * @return the value of F_FILE.SUFFIX
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.SUFFIX
     *
     * @param suffix the value for F_FILE.SUFFIX
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.FILESIZE
     *
     * @return the value of F_FILE.FILESIZE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public BigDecimal getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.FILESIZE
     *
     * @param filesize the value for F_FILE.FILESIZE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setFilesize(BigDecimal filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.MD5
     *
     * @return the value of F_FILE.MD5
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.MD5
     *
     * @param md5 the value for F_FILE.MD5
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.FK_VALUELIST_KEY
     *
     * @return the value of F_FILE.FK_VALUELIST_KEY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getFkValuelistKey() {
        return fkValuelistKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.FK_VALUELIST_KEY
     *
     * @param fkValuelistKey the value for F_FILE.FK_VALUELIST_KEY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setFkValuelistKey(String fkValuelistKey) {
        this.fkValuelistKey = fkValuelistKey == null ? null : fkValuelistKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.SERVERSIDEPATH
     *
     * @return the value of F_FILE.SERVERSIDEPATH
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getServersidepath() {
        return serversidepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.SERVERSIDEPATH
     *
     * @param serversidepath the value for F_FILE.SERVERSIDEPATH
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setServersidepath(String serversidepath) {
        this.serversidepath = serversidepath == null ? null : serversidepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.UPLOADINGUSER
     *
     * @return the value of F_FILE.UPLOADINGUSER
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getUploadinguser() {
        return uploadinguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.UPLOADINGUSER
     *
     * @param uploadinguser the value for F_FILE.UPLOADINGUSER
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setUploadinguser(String uploadinguser) {
        this.uploadinguser = uploadinguser == null ? null : uploadinguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.NOTE
     *
     * @return the value of F_FILE.NOTE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.NOTE
     *
     * @param note the value for F_FILE.NOTE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.ISDELETE
     *
     * @return the value of F_FILE.ISDELETE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.ISDELETE
     *
     * @param isdelete the value for F_FILE.ISDELETE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.CREATEAT
     *
     * @return the value of F_FILE.CREATEAT
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.CREATEAT
     *
     * @param createat the value for F_FILE.CREATEAT
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.CREATEBY
     *
     * @return the value of F_FILE.CREATEBY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.CREATEBY
     *
     * @param createby the value for F_FILE.CREATEBY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.UPDATEAT
     *
     * @return the value of F_FILE.UPDATEAT
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.UPDATEAT
     *
     * @param updateat the value for F_FILE.UPDATEAT
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_FILE.UPDATEBY
     *
     * @return the value of F_FILE.UPDATEBY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_FILE.UPDATEBY
     *
     * @param updateby the value for F_FILE.UPDATEBY
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }
}