package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ItemBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.ITEM_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.NAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.FK_ITEM_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String fkItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.REMARK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_ITEM.ICON
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.ITEM_ID
     *
     * @return the value of F_ITEM.ITEM_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.ITEM_ID
     *
     * @param itemId the value for F_ITEM.ITEM_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.NAME
     *
     * @return the value of F_ITEM.NAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.NAME
     *
     * @param name the value for F_ITEM.NAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.FK_ITEM_ID
     *
     * @return the value of F_ITEM.FK_ITEM_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getFkItemId() {
        return fkItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.FK_ITEM_ID
     *
     * @param fkItemId the value for F_ITEM.FK_ITEM_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setFkItemId(String fkItemId) {
        this.fkItemId = fkItemId == null ? null : fkItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.REMARK
     *
     * @return the value of F_ITEM.REMARK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.REMARK
     *
     * @param remark the value for F_ITEM.REMARK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.ISDELETE
     *
     * @return the value of F_ITEM.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.ISDELETE
     *
     * @param isdelete the value for F_ITEM.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.CREATEAT
     *
     * @return the value of F_ITEM.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.CREATEAT
     *
     * @param createat the value for F_ITEM.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.CREATEBY
     *
     * @return the value of F_ITEM.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.CREATEBY
     *
     * @param createby the value for F_ITEM.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.UPDATEAT
     *
     * @return the value of F_ITEM.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.UPDATEAT
     *
     * @param updateat the value for F_ITEM.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.UPDATEBY
     *
     * @return the value of F_ITEM.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.UPDATEBY
     *
     * @param updateby the value for F_ITEM.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_ITEM.ICON
     *
     * @return the value of F_ITEM.ICON
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_ITEM.ICON
     *
     * @param icon the value for F_ITEM.ICON
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}