package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MeunBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.MENU_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.FK_MENU_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String fkMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.MENUDISPLAYNAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String menudisplayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.MENULINK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String menulink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.ICON
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.ISSHOW
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.ISPAGE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal ispage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.ORDERNO
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.NOTE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_MENU.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.MENU_ID
     *
     * @return the value of F_MENU.MENU_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.MENU_ID
     *
     * @param menuId the value for F_MENU.MENU_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.FK_MENU_ID
     *
     * @return the value of F_MENU.FK_MENU_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getFkMenuId() {
        return fkMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.FK_MENU_ID
     *
     * @param fkMenuId the value for F_MENU.FK_MENU_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setFkMenuId(String fkMenuId) {
        this.fkMenuId = fkMenuId == null ? null : fkMenuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.MENUDISPLAYNAME
     *
     * @return the value of F_MENU.MENUDISPLAYNAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getMenudisplayname() {
        return menudisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.MENUDISPLAYNAME
     *
     * @param menudisplayname the value for F_MENU.MENUDISPLAYNAME
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setMenudisplayname(String menudisplayname) {
        this.menudisplayname = menudisplayname == null ? null : menudisplayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.MENULINK
     *
     * @return the value of F_MENU.MENULINK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getMenulink() {
        return menulink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.MENULINK
     *
     * @param menulink the value for F_MENU.MENULINK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setMenulink(String menulink) {
        this.menulink = menulink == null ? null : menulink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.ICON
     *
     * @return the value of F_MENU.ICON
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.ICON
     *
     * @param icon the value for F_MENU.ICON
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.ISSHOW
     *
     * @return the value of F_MENU.ISSHOW
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.ISSHOW
     *
     * @param isshow the value for F_MENU.ISSHOW
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIsshow(BigDecimal isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.ISPAGE
     *
     * @return the value of F_MENU.ISPAGE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIspage() {
        return ispage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.ISPAGE
     *
     * @param ispage the value for F_MENU.ISPAGE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIspage(BigDecimal ispage) {
        this.ispage = ispage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.ORDERNO
     *
     * @return the value of F_MENU.ORDERNO
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.ORDERNO
     *
     * @param orderno the value for F_MENU.ORDERNO
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setOrderno(BigDecimal orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.NOTE
     *
     * @return the value of F_MENU.NOTE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.NOTE
     *
     * @param note the value for F_MENU.NOTE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.ISDELETE
     *
     * @return the value of F_MENU.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.ISDELETE
     *
     * @param isdelete the value for F_MENU.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.CREATEAT
     *
     * @return the value of F_MENU.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.CREATEAT
     *
     * @param createat the value for F_MENU.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.CREATEBY
     *
     * @return the value of F_MENU.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.CREATEBY
     *
     * @param createby the value for F_MENU.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.UPDATEAT
     *
     * @return the value of F_MENU.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.UPDATEAT
     *
     * @param updateat the value for F_MENU.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_MENU.UPDATEBY
     *
     * @return the value of F_MENU.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_MENU.UPDATEBY
     *
     * @param updateby the value for F_MENU.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }
}