package com.intest.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PackageTaskBtoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public PackageTaskBtoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPackagetaskIdIsNull() {
            addCriterion("PACKAGETASK_ID is null");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdIsNotNull() {
            addCriterion("PACKAGETASK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdEqualTo(String value) {
            addCriterion("PACKAGETASK_ID =", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdNotEqualTo(String value) {
            addCriterion("PACKAGETASK_ID <>", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdGreaterThan(String value) {
            addCriterion("PACKAGETASK_ID >", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("PACKAGETASK_ID >=", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdLessThan(String value) {
            addCriterion("PACKAGETASK_ID <", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdLessThanOrEqualTo(String value) {
            addCriterion("PACKAGETASK_ID <=", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdLike(String value) {
            addCriterion("PACKAGETASK_ID like", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdNotLike(String value) {
            addCriterion("PACKAGETASK_ID not like", value, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdIn(List<String> values) {
            addCriterion("PACKAGETASK_ID in", values, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdNotIn(List<String> values) {
            addCriterion("PACKAGETASK_ID not in", values, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdBetween(String value1, String value2) {
            addCriterion("PACKAGETASK_ID between", value1, value2, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andPackagetaskIdNotBetween(String value1, String value2) {
            addCriterion("PACKAGETASK_ID not between", value1, value2, "packagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdIsNull() {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdIsNotNull() {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdEqualTo(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID =", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdNotEqualTo(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID <>", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdGreaterThan(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID >", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID >=", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdLessThan(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID <", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdLessThanOrEqualTo(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID <=", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdLike(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID like", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdNotLike(String value) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID not like", value, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdIn(List<String> values) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID in", values, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdNotIn(List<String> values) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID not in", values, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdBetween(String value1, String value2) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID between", value1, value2, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkCarpackagemaketypeIdNotBetween(String value1, String value2) {
            addCriterion("FK_CARPACKAGEMAKETYPE_ID not between", value1, value2, "fkCarpackagemaketypeId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeIsNull() {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeIsNotNull() {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeEqualTo(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE =", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeNotEqualTo(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE <>", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeGreaterThan(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE >", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE >=", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeLessThan(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE <", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeLessThanOrEqualTo(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE <=", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeLike(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE like", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeNotLike(String value) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE not like", value, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeIn(List<String> values) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE in", values, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeNotIn(List<String> values) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE not in", values, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeBetween(String value1, String value2) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE between", value1, value2, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskstatusvalueCodeNotBetween(String value1, String value2) {
            addCriterion("FK_PACKAGETASKSTATUSVALUE_CODE not between", value1, value2, "fkPackagetaskstatusvalueCode");
            return (Criteria) this;
        }

        public Criteria andCreateatIsNull() {
            addCriterion("CREATEAT is null");
            return (Criteria) this;
        }

        public Criteria andCreateatIsNotNull() {
            addCriterion("CREATEAT is not null");
            return (Criteria) this;
        }

        public Criteria andCreateatEqualTo(Date value) {
            addCriterion("CREATEAT =", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotEqualTo(Date value) {
            addCriterion("CREATEAT <>", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatGreaterThan(Date value) {
            addCriterion("CREATEAT >", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEAT >=", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatLessThan(Date value) {
            addCriterion("CREATEAT <", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatLessThanOrEqualTo(Date value) {
            addCriterion("CREATEAT <=", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatIn(List<Date> values) {
            addCriterion("CREATEAT in", values, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotIn(List<Date> values) {
            addCriterion("CREATEAT not in", values, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatBetween(Date value1, Date value2) {
            addCriterion("CREATEAT between", value1, value2, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotBetween(Date value1, Date value2) {
            addCriterion("CREATEAT not between", value1, value2, "createat");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("CREATEBY =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("CREATEBY <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("CREATEBY >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEBY >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("CREATEBY <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("CREATEBY <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("CREATEBY like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("CREATEBY not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("CREATEBY in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("CREATEBY not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("CREATEBY between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("CREATEBY not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdateatIsNull() {
            addCriterion("UPDATEAT is null");
            return (Criteria) this;
        }

        public Criteria andUpdateatIsNotNull() {
            addCriterion("UPDATEAT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateatEqualTo(Date value) {
            addCriterion("UPDATEAT =", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatNotEqualTo(Date value) {
            addCriterion("UPDATEAT <>", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatGreaterThan(Date value) {
            addCriterion("UPDATEAT >", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEAT >=", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatLessThan(Date value) {
            addCriterion("UPDATEAT <", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatLessThanOrEqualTo(Date value) {
            addCriterion("UPDATEAT <=", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatIn(List<Date> values) {
            addCriterion("UPDATEAT in", values, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatNotIn(List<Date> values) {
            addCriterion("UPDATEAT not in", values, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatBetween(Date value1, Date value2) {
            addCriterion("UPDATEAT between", value1, value2, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatNotBetween(Date value1, Date value2) {
            addCriterion("UPDATEAT not between", value1, value2, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("UPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("UPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(String value) {
            addCriterion("UPDATEBY =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(String value) {
            addCriterion("UPDATEBY <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(String value) {
            addCriterion("UPDATEBY >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEBY >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(String value) {
            addCriterion("UPDATEBY <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(String value) {
            addCriterion("UPDATEBY <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLike(String value) {
            addCriterion("UPDATEBY like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotLike(String value) {
            addCriterion("UPDATEBY not like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<String> values) {
            addCriterion("UPDATEBY in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<String> values) {
            addCriterion("UPDATEBY not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(String value1, String value2) {
            addCriterion("UPDATEBY between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(String value1, String value2) {
            addCriterion("UPDATEBY not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdIsNull() {
            addCriterion("FK_CARTYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdIsNotNull() {
            addCriterion("FK_CARTYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdEqualTo(String value) {
            addCriterion("FK_CARTYPE_ID =", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdNotEqualTo(String value) {
            addCriterion("FK_CARTYPE_ID <>", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdGreaterThan(String value) {
            addCriterion("FK_CARTYPE_ID >", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_CARTYPE_ID >=", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdLessThan(String value) {
            addCriterion("FK_CARTYPE_ID <", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdLessThanOrEqualTo(String value) {
            addCriterion("FK_CARTYPE_ID <=", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdLike(String value) {
            addCriterion("FK_CARTYPE_ID like", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdNotLike(String value) {
            addCriterion("FK_CARTYPE_ID not like", value, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdIn(List<String> values) {
            addCriterion("FK_CARTYPE_ID in", values, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdNotIn(List<String> values) {
            addCriterion("FK_CARTYPE_ID not in", values, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdBetween(String value1, String value2) {
            addCriterion("FK_CARTYPE_ID between", value1, value2, "fkCartypeId");
            return (Criteria) this;
        }

        public Criteria andFkCartypeIdNotBetween(String value1, String value2) {
            addCriterion("FK_CARTYPE_ID not between", value1, value2, "fkCartypeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 07 10:48:39 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table F_PACKAGETASK
     *
     * @mbg.generated Mon Sep 07 10:48:39 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}