package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PartsUpgradePackageBtoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public PartsUpgradePackageBtoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPartsupgradepackageIdIsNull() {
            addCriterion("PARTSUPGRADEPACKAGE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdIsNotNull() {
            addCriterion("PARTSUPGRADEPACKAGE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdEqualTo(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID =", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdNotEqualTo(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID <>", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdGreaterThan(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID >", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID >=", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdLessThan(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID <", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdLessThanOrEqualTo(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID <=", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdLike(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID like", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdNotLike(String value) {
            addCriterion("PARTSUPGRADEPACKAGE_ID not like", value, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdIn(List<String> values) {
            addCriterion("PARTSUPGRADEPACKAGE_ID in", values, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdNotIn(List<String> values) {
            addCriterion("PARTSUPGRADEPACKAGE_ID not in", values, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdBetween(String value1, String value2) {
            addCriterion("PARTSUPGRADEPACKAGE_ID between", value1, value2, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andPartsupgradepackageIdNotBetween(String value1, String value2) {
            addCriterion("PARTSUPGRADEPACKAGE_ID not between", value1, value2, "partsupgradepackageId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdIsNull() {
            addCriterion("FK_PACKAGETASK_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdIsNotNull() {
            addCriterion("FK_PACKAGETASK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdEqualTo(String value) {
            addCriterion("FK_PACKAGETASK_ID =", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdNotEqualTo(String value) {
            addCriterion("FK_PACKAGETASK_ID <>", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdGreaterThan(String value) {
            addCriterion("FK_PACKAGETASK_ID >", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_PACKAGETASK_ID >=", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdLessThan(String value) {
            addCriterion("FK_PACKAGETASK_ID <", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdLessThanOrEqualTo(String value) {
            addCriterion("FK_PACKAGETASK_ID <=", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdLike(String value) {
            addCriterion("FK_PACKAGETASK_ID like", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdNotLike(String value) {
            addCriterion("FK_PACKAGETASK_ID not like", value, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdIn(List<String> values) {
            addCriterion("FK_PACKAGETASK_ID in", values, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdNotIn(List<String> values) {
            addCriterion("FK_PACKAGETASK_ID not in", values, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdBetween(String value1, String value2) {
            addCriterion("FK_PACKAGETASK_ID between", value1, value2, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkPackagetaskIdNotBetween(String value1, String value2) {
            addCriterion("FK_PACKAGETASK_ID not between", value1, value2, "fkPackagetaskId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdIsNull() {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdIsNotNull() {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID =", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdNotEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID <>", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdGreaterThan(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID >", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID >=", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdLessThan(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID <", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdLessThanOrEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID <=", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdLike(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID like", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdNotLike(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID not like", value, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdIn(List<String> values) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID in", values, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdNotIn(List<String> values) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID not in", values, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBetween(String value1, String value2) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID between", value1, value2, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdNotBetween(String value1, String value2) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID not between", value1, value2, "fkUpgradepackagefileinfoId");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("ISDELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("ISDELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(BigDecimal value) {
            addCriterion("ISDELETE =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(BigDecimal value) {
            addCriterion("ISDELETE <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(BigDecimal value) {
            addCriterion("ISDELETE >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISDELETE >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(BigDecimal value) {
            addCriterion("ISDELETE <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISDELETE <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<BigDecimal> values) {
            addCriterion("ISDELETE in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<BigDecimal> values) {
            addCriterion("ISDELETE not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISDELETE between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISDELETE not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andCreateatIsNull() {
            addCriterion("CREATEAT is null");
            return (Criteria) this;
        }

        public Criteria andCreateatIsNotNull() {
            addCriterion("CREATEAT is not null");
            return (Criteria) this;
        }

        public Criteria andCreateatEqualTo(Date value) {
            addCriterion("CREATEAT =", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotEqualTo(Date value) {
            addCriterion("CREATEAT <>", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatGreaterThan(Date value) {
            addCriterion("CREATEAT >", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEAT >=", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatLessThan(Date value) {
            addCriterion("CREATEAT <", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatLessThanOrEqualTo(Date value) {
            addCriterion("CREATEAT <=", value, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatIn(List<Date> values) {
            addCriterion("CREATEAT in", values, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotIn(List<Date> values) {
            addCriterion("CREATEAT not in", values, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatBetween(Date value1, Date value2) {
            addCriterion("CREATEAT between", value1, value2, "createat");
            return (Criteria) this;
        }

        public Criteria andCreateatNotBetween(Date value1, Date value2) {
            addCriterion("CREATEAT not between", value1, value2, "createat");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("CREATEBY is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("CREATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("CREATEBY =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("CREATEBY <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("CREATEBY >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEBY >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("CREATEBY <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("CREATEBY <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("CREATEBY like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("CREATEBY not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("CREATEBY in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("CREATEBY not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("CREATEBY between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("CREATEBY not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andUpdateatIsNull() {
            addCriterion("UPDATEAT is null");
            return (Criteria) this;
        }

        public Criteria andUpdateatIsNotNull() {
            addCriterion("UPDATEAT is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateatEqualTo(Date value) {
            addCriterion("UPDATEAT =", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatNotEqualTo(Date value) {
            addCriterion("UPDATEAT <>", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatGreaterThan(Date value) {
            addCriterion("UPDATEAT >", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATEAT >=", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatLessThan(Date value) {
            addCriterion("UPDATEAT <", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatLessThanOrEqualTo(Date value) {
            addCriterion("UPDATEAT <=", value, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatIn(List<Date> values) {
            addCriterion("UPDATEAT in", values, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatNotIn(List<Date> values) {
            addCriterion("UPDATEAT not in", values, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatBetween(Date value1, Date value2) {
            addCriterion("UPDATEAT between", value1, value2, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdateatNotBetween(Date value1, Date value2) {
            addCriterion("UPDATEAT not between", value1, value2, "updateat");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNull() {
            addCriterion("UPDATEBY is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIsNotNull() {
            addCriterion("UPDATEBY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyEqualTo(String value) {
            addCriterion("UPDATEBY =", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotEqualTo(String value) {
            addCriterion("UPDATEBY <>", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThan(String value) {
            addCriterion("UPDATEBY >", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATEBY >=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThan(String value) {
            addCriterion("UPDATEBY <", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLessThanOrEqualTo(String value) {
            addCriterion("UPDATEBY <=", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyLike(String value) {
            addCriterion("UPDATEBY like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotLike(String value) {
            addCriterion("UPDATEBY not like", value, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyIn(List<String> values) {
            addCriterion("UPDATEBY in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotIn(List<String> values) {
            addCriterion("UPDATEBY not in", values, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyBetween(String value1, String value2) {
            addCriterion("UPDATEBY between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andUpdatebyNotBetween(String value1, String value2) {
            addCriterion("UPDATEBY not between", value1, value2, "updateby");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBIsNull() {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B is null");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBIsNotNull() {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B is not null");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B =", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBNotEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B <>", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBGreaterThan(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B >", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBGreaterThanOrEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B >=", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBLessThan(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B <", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBLessThanOrEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B <=", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBLike(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B like", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBNotLike(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B not like", value, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBIn(List<String> values) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B in", values, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBNotIn(List<String> values) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B not in", values, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBBetween(String value1, String value2) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B between", value1, value2, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdBNotBetween(String value1, String value2) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_B not between", value1, value2, "fkUpgradepackagefileinfoIdB");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHIsNull() {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H is null");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHIsNotNull() {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H is not null");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H =", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHNotEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H <>", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHGreaterThan(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H >", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHGreaterThanOrEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H >=", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHLessThan(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H <", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHLessThanOrEqualTo(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H <=", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHLike(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H like", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHNotLike(String value) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H not like", value, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHIn(List<String> values) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H in", values, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHNotIn(List<String> values) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H not in", values, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHBetween(String value1, String value2) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H between", value1, value2, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }

        public Criteria andFkUpgradepackagefileinfoIdHNotBetween(String value1, String value2) {
            addCriterion("FK_UPGRADEPACKAGEFILEINFO_ID_H not between", value1, value2, "fkUpgradepackagefileinfoIdH");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 03 14:49:42 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}