package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PartsUpgradePackageBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.PARTSUPGRADEPACKAGE_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String partsupgradepackageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.FK_PACKAGETASK_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String fkPackagetaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String fkUpgradepackagefileinfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.ISDELETE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.CREATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.CREATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.UPDATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.UPDATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_B
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String fkUpgradepackagefileinfoIdB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_H
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String fkUpgradepackagefileinfoIdH;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.PARTSUPGRADEPACKAGE_ID
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.PARTSUPGRADEPACKAGE_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getPartsupgradepackageId() {
        return partsupgradepackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.PARTSUPGRADEPACKAGE_ID
     *
     * @param partsupgradepackageId the value for F_PARTSUPGRADEPACKAGE.PARTSUPGRADEPACKAGE_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setPartsupgradepackageId(String partsupgradepackageId) {
        this.partsupgradepackageId = partsupgradepackageId == null ? null : partsupgradepackageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.FK_PACKAGETASK_ID
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.FK_PACKAGETASK_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getFkPackagetaskId() {
        return fkPackagetaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.FK_PACKAGETASK_ID
     *
     * @param fkPackagetaskId the value for F_PARTSUPGRADEPACKAGE.FK_PACKAGETASK_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFkPackagetaskId(String fkPackagetaskId) {
        this.fkPackagetaskId = fkPackagetaskId == null ? null : fkPackagetaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getFkUpgradepackagefileinfoId() {
        return fkUpgradepackagefileinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID
     *
     * @param fkUpgradepackagefileinfoId the value for F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFkUpgradepackagefileinfoId(String fkUpgradepackagefileinfoId) {
        this.fkUpgradepackagefileinfoId = fkUpgradepackagefileinfoId == null ? null : fkUpgradepackagefileinfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.ISDELETE
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.ISDELETE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.ISDELETE
     *
     * @param isdelete the value for F_PARTSUPGRADEPACKAGE.ISDELETE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.CREATEAT
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.CREATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.CREATEAT
     *
     * @param createat the value for F_PARTSUPGRADEPACKAGE.CREATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.CREATEBY
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.CREATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.CREATEBY
     *
     * @param createby the value for F_PARTSUPGRADEPACKAGE.CREATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.UPDATEAT
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.UPDATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.UPDATEAT
     *
     * @param updateat the value for F_PARTSUPGRADEPACKAGE.UPDATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.UPDATEBY
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.UPDATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.UPDATEBY
     *
     * @param updateby the value for F_PARTSUPGRADEPACKAGE.UPDATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_B
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_B
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getFkUpgradepackagefileinfoIdB() {
        return fkUpgradepackagefileinfoIdB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_B
     *
     * @param fkUpgradepackagefileinfoIdB the value for F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_B
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFkUpgradepackagefileinfoIdB(String fkUpgradepackagefileinfoIdB) {
        this.fkUpgradepackagefileinfoIdB = fkUpgradepackagefileinfoIdB == null ? null : fkUpgradepackagefileinfoIdB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_H
     *
     * @return the value of F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_H
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getFkUpgradepackagefileinfoIdH() {
        return fkUpgradepackagefileinfoIdH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_H
     *
     * @param fkUpgradepackagefileinfoIdH the value for F_PARTSUPGRADEPACKAGE.FK_UPGRADEPACKAGEFILEINFO_ID_H
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFkUpgradepackagefileinfoIdH(String fkUpgradepackagefileinfoIdH) {
        this.fkUpgradepackagefileinfoIdH = fkUpgradepackagefileinfoIdH == null ? null : fkUpgradepackagefileinfoIdH.trim();
    }
}