package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PartsBigPackageBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.PARTSBIGPACKAGE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private String partsbigpackageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.FK_FILE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private String fkFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.FK_CARTYPE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private String fkCartypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.REMARK
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.ISDELETE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.CREATEAT
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.CREATEBY
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.UPDATEAT
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_PARTSBIGPACKAGE.UPDATEBY
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.PARTSBIGPACKAGE_ID
     *
     * @return the value of F_PARTSBIGPACKAGE.PARTSBIGPACKAGE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public String getPartsbigpackageId() {
        return partsbigpackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.PARTSBIGPACKAGE_ID
     *
     * @param partsbigpackageId the value for F_PARTSBIGPACKAGE.PARTSBIGPACKAGE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setPartsbigpackageId(String partsbigpackageId) {
        this.partsbigpackageId = partsbigpackageId == null ? null : partsbigpackageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.FK_FILE_ID
     *
     * @return the value of F_PARTSBIGPACKAGE.FK_FILE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public String getFkFileId() {
        return fkFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.FK_FILE_ID
     *
     * @param fkFileId the value for F_PARTSBIGPACKAGE.FK_FILE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setFkFileId(String fkFileId) {
        this.fkFileId = fkFileId == null ? null : fkFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.FK_CARTYPE_ID
     *
     * @return the value of F_PARTSBIGPACKAGE.FK_CARTYPE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public String getFkCartypeId() {
        return fkCartypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.FK_CARTYPE_ID
     *
     * @param fkCartypeId the value for F_PARTSBIGPACKAGE.FK_CARTYPE_ID
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setFkCartypeId(String fkCartypeId) {
        this.fkCartypeId = fkCartypeId == null ? null : fkCartypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.REMARK
     *
     * @return the value of F_PARTSBIGPACKAGE.REMARK
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.REMARK
     *
     * @param remark the value for F_PARTSBIGPACKAGE.REMARK
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.ISDELETE
     *
     * @return the value of F_PARTSBIGPACKAGE.ISDELETE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.ISDELETE
     *
     * @param isdelete the value for F_PARTSBIGPACKAGE.ISDELETE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.CREATEAT
     *
     * @return the value of F_PARTSBIGPACKAGE.CREATEAT
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.CREATEAT
     *
     * @param createat the value for F_PARTSBIGPACKAGE.CREATEAT
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.CREATEBY
     *
     * @return the value of F_PARTSBIGPACKAGE.CREATEBY
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.CREATEBY
     *
     * @param createby the value for F_PARTSBIGPACKAGE.CREATEBY
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.UPDATEAT
     *
     * @return the value of F_PARTSBIGPACKAGE.UPDATEAT
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.UPDATEAT
     *
     * @param updateat the value for F_PARTSBIGPACKAGE.UPDATEAT
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_PARTSBIGPACKAGE.UPDATEBY
     *
     * @return the value of F_PARTSBIGPACKAGE.UPDATEBY
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_PARTSBIGPACKAGE.UPDATEBY
     *
     * @param updateby the value for F_PARTSBIGPACKAGE.UPDATEBY
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }
}