package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TaskOriginalPackageBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.TASKORIGINALPACKAGE_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private String taskoriginalpackageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.FK_PACKAGETASK_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private String fkPackagetaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.FK_PARTSPACKAGE_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private String fkPartspackageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.TYPE
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private BigDecimal type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.CREATEAT
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.CREATEBY
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.UPDATEAT
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TASKORIGINALPACKAGE.UPDATEBY
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.TASKORIGINALPACKAGE_ID
     *
     * @return the value of F_TASKORIGINALPACKAGE.TASKORIGINALPACKAGE_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public String getTaskoriginalpackageId() {
        return taskoriginalpackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.TASKORIGINALPACKAGE_ID
     *
     * @param taskoriginalpackageId the value for F_TASKORIGINALPACKAGE.TASKORIGINALPACKAGE_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setTaskoriginalpackageId(String taskoriginalpackageId) {
        this.taskoriginalpackageId = taskoriginalpackageId == null ? null : taskoriginalpackageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.FK_PACKAGETASK_ID
     *
     * @return the value of F_TASKORIGINALPACKAGE.FK_PACKAGETASK_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public String getFkPackagetaskId() {
        return fkPackagetaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.FK_PACKAGETASK_ID
     *
     * @param fkPackagetaskId the value for F_TASKORIGINALPACKAGE.FK_PACKAGETASK_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setFkPackagetaskId(String fkPackagetaskId) {
        this.fkPackagetaskId = fkPackagetaskId == null ? null : fkPackagetaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.FK_PARTSPACKAGE_ID
     *
     * @return the value of F_TASKORIGINALPACKAGE.FK_PARTSPACKAGE_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public String getFkPartspackageId() {
        return fkPartspackageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.FK_PARTSPACKAGE_ID
     *
     * @param fkPartspackageId the value for F_TASKORIGINALPACKAGE.FK_PARTSPACKAGE_ID
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setFkPartspackageId(String fkPartspackageId) {
        this.fkPartspackageId = fkPartspackageId == null ? null : fkPartspackageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.TYPE
     *
     * @return the value of F_TASKORIGINALPACKAGE.TYPE
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.TYPE
     *
     * @param type the value for F_TASKORIGINALPACKAGE.TYPE
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.CREATEAT
     *
     * @return the value of F_TASKORIGINALPACKAGE.CREATEAT
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.CREATEAT
     *
     * @param createat the value for F_TASKORIGINALPACKAGE.CREATEAT
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.CREATEBY
     *
     * @return the value of F_TASKORIGINALPACKAGE.CREATEBY
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.CREATEBY
     *
     * @param createby the value for F_TASKORIGINALPACKAGE.CREATEBY
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.UPDATEAT
     *
     * @return the value of F_TASKORIGINALPACKAGE.UPDATEAT
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.UPDATEAT
     *
     * @param updateat the value for F_TASKORIGINALPACKAGE.UPDATEAT
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TASKORIGINALPACKAGE.UPDATEBY
     *
     * @return the value of F_TASKORIGINALPACKAGE.UPDATEBY
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TASKORIGINALPACKAGE.UPDATEBY
     *
     * @param updateby the value for F_TASKORIGINALPACKAGE.UPDATEBY
     *
     * @mbg.generated Mon Sep 14 14:42:49 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }
}