package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ToolbarBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.TOOLBAR_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String toolbarId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.CHARECKED
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal charecked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.REMARK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_TOOLBAR.FK_TABLE_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    private String fkTableId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.TOOLBAR_ID
     *
     * @return the value of F_TOOLBAR.TOOLBAR_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getToolbarId() {
        return toolbarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.TOOLBAR_ID
     *
     * @param toolbarId the value for F_TOOLBAR.TOOLBAR_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setToolbarId(String toolbarId) {
        this.toolbarId = toolbarId == null ? null : toolbarId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.CHARECKED
     *
     * @return the value of F_TOOLBAR.CHARECKED
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getCharecked() {
        return charecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.CHARECKED
     *
     * @param charecked the value for F_TOOLBAR.CHARECKED
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCharecked(BigDecimal charecked) {
        this.charecked = charecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.REMARK
     *
     * @return the value of F_TOOLBAR.REMARK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.REMARK
     *
     * @param remark the value for F_TOOLBAR.REMARK
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.ISDELETE
     *
     * @return the value of F_TOOLBAR.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.ISDELETE
     *
     * @param isdelete the value for F_TOOLBAR.ISDELETE
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.CREATEAT
     *
     * @return the value of F_TOOLBAR.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.CREATEAT
     *
     * @param createat the value for F_TOOLBAR.CREATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.CREATEBY
     *
     * @return the value of F_TOOLBAR.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.CREATEBY
     *
     * @param createby the value for F_TOOLBAR.CREATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.UPDATEAT
     *
     * @return the value of F_TOOLBAR.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.UPDATEAT
     *
     * @param updateat the value for F_TOOLBAR.UPDATEAT
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.UPDATEBY
     *
     * @return the value of F_TOOLBAR.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.UPDATEBY
     *
     * @param updateby the value for F_TOOLBAR.UPDATEBY
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_TOOLBAR.FK_TABLE_ID
     *
     * @return the value of F_TOOLBAR.FK_TABLE_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public String getFkTableId() {
        return fkTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_TOOLBAR.FK_TABLE_ID
     *
     * @param fkTableId the value for F_TOOLBAR.FK_TABLE_ID
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    public void setFkTableId(String fkTableId) {
        this.fkTableId = fkTableId == null ? null : fkTableId.trim();
    }
}