package com.intest.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UpgradePackageFileinfoBto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.UPGRADEPACKAGEFILEINFO_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String upgradepackagefileinfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.SUFFIX
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.FILESIZE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private BigDecimal filesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.MD5
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.ISDELETE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private BigDecimal isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.CREATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private Date createat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.CREATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.UPDATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private Date updateat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.UPDATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String updateby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.FILENAME
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.FK_VALUELIST_KEY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private String fkValuelistKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column F_UPGRADEPACKAGEFILEINFO.ISPUBLISH
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    private BigDecimal ispublish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.UPGRADEPACKAGEFILEINFO_ID
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.UPGRADEPACKAGEFILEINFO_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getUpgradepackagefileinfoId() {
        return upgradepackagefileinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.UPGRADEPACKAGEFILEINFO_ID
     *
     * @param upgradepackagefileinfoId the value for F_UPGRADEPACKAGEFILEINFO.UPGRADEPACKAGEFILEINFO_ID
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setUpgradepackagefileinfoId(String upgradepackagefileinfoId) {
        this.upgradepackagefileinfoId = upgradepackagefileinfoId == null ? null : upgradepackagefileinfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.SUFFIX
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.SUFFIX
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.SUFFIX
     *
     * @param suffix the value for F_UPGRADEPACKAGEFILEINFO.SUFFIX
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.FILESIZE
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.FILESIZE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public BigDecimal getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.FILESIZE
     *
     * @param filesize the value for F_UPGRADEPACKAGEFILEINFO.FILESIZE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFilesize(BigDecimal filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.MD5
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.MD5
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.MD5
     *
     * @param md5 the value for F_UPGRADEPACKAGEFILEINFO.MD5
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.ISDELETE
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.ISDELETE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public BigDecimal getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.ISDELETE
     *
     * @param isdelete the value for F_UPGRADEPACKAGEFILEINFO.ISDELETE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setIsdelete(BigDecimal isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.CREATEAT
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.CREATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public Date getCreateat() {
        return createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.CREATEAT
     *
     * @param createat the value for F_UPGRADEPACKAGEFILEINFO.CREATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setCreateat(Date createat) {
        this.createat = createat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.CREATEBY
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.CREATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.CREATEBY
     *
     * @param createby the value for F_UPGRADEPACKAGEFILEINFO.CREATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.UPDATEAT
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.UPDATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public Date getUpdateat() {
        return updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.UPDATEAT
     *
     * @param updateat the value for F_UPGRADEPACKAGEFILEINFO.UPDATEAT
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setUpdateat(Date updateat) {
        this.updateat = updateat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.UPDATEBY
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.UPDATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.UPDATEBY
     *
     * @param updateby the value for F_UPGRADEPACKAGEFILEINFO.UPDATEBY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.FILENAME
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.FILENAME
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.FILENAME
     *
     * @param filename the value for F_UPGRADEPACKAGEFILEINFO.FILENAME
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.FK_VALUELIST_KEY
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.FK_VALUELIST_KEY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public String getFkValuelistKey() {
        return fkValuelistKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.FK_VALUELIST_KEY
     *
     * @param fkValuelistKey the value for F_UPGRADEPACKAGEFILEINFO.FK_VALUELIST_KEY
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setFkValuelistKey(String fkValuelistKey) {
        this.fkValuelistKey = fkValuelistKey == null ? null : fkValuelistKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column F_UPGRADEPACKAGEFILEINFO.ISPUBLISH
     *
     * @return the value of F_UPGRADEPACKAGEFILEINFO.ISPUBLISH
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public BigDecimal getIspublish() {
        return ispublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column F_UPGRADEPACKAGEFILEINFO.ISPUBLISH
     *
     * @param ispublish the value for F_UPGRADEPACKAGEFILEINFO.ISPUBLISH
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    public void setIspublish(BigDecimal ispublish) {
        this.ispublish = ispublish;
    }
}