package com.intest.dao.mapper;

import com.intest.dao.entity.ColumnOptionBto;
import com.intest.dao.entity.ColumnOptionBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnOptionBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    long countByExample(ColumnOptionBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByExample(ColumnOptionBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByPrimaryKey(String columnoptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insert(ColumnOptionBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insertSelective(ColumnOptionBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    List<ColumnOptionBto> selectByExample(ColumnOptionBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    ColumnOptionBto selectByPrimaryKey(String columnoptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") ColumnOptionBto record, @Param("example") ColumnOptionBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExample(@Param("record") ColumnOptionBto record, @Param("example") ColumnOptionBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKeySelective(ColumnOptionBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMNOPTION
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKey(ColumnOptionBto record);
}