package com.intest.dao.mapper;

import com.intest.dao.entity.ColumnBto;
import com.intest.dao.entity.ColumnBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    long countByExample(ColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByExample(ColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByPrimaryKey(String columnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insert(ColumnBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insertSelective(ColumnBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    List<ColumnBto> selectByExample(ColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    ColumnBto selectByPrimaryKey(String columnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") ColumnBto record, @Param("example") ColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExample(@Param("record") ColumnBto record, @Param("example") ColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKeySelective(ColumnBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_COLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKey(ColumnBto record);
}