package com.intest.dao.mapper;

import com.intest.dao.entity.FileBto;
import com.intest.dao.entity.FileBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    long countByExample(FileBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int deleteByExample(FileBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int insert(FileBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int insertSelective(FileBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    List<FileBto> selectByExample(FileBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    FileBto selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int updateByExampleSelective(@Param("record") FileBto record, @Param("example") FileBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int updateByExample(@Param("record") FileBto record, @Param("example") FileBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int updateByPrimaryKeySelective(FileBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_FILE
     *
     * @mbg.generated Mon Aug 31 15:43:45 CST 2020
     */
    int updateByPrimaryKey(FileBto record);
}