package com.intest.dao.mapper;

import com.intest.dao.entity.MeunBto;
import com.intest.dao.entity.MeunBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeunBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    long countByExample(MeunBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByExample(MeunBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insert(MeunBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insertSelective(MeunBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    List<MeunBto> selectByExample(MeunBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    MeunBto selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") MeunBto record, @Param("example") MeunBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExample(@Param("record") MeunBto record, @Param("example") MeunBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKeySelective(MeunBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_MENU
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKey(MeunBto record);
}