package com.intest.dao.mapper;

import com.intest.dao.entity.PartsBto;
import com.intest.dao.entity.PartsBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    long countByExample(PartsBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int deleteByExample(PartsBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int deleteByPrimaryKey(String partsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int insert(PartsBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int insertSelective(PartsBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    List<PartsBto> selectByExample(PartsBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    PartsBto selectByPrimaryKey(String partsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") PartsBto record, @Param("example") PartsBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByExample(@Param("record") PartsBto record, @Param("example") PartsBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByPrimaryKeySelective(PartsBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTS
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByPrimaryKey(PartsBto record);
}