package com.intest.dao.mapper;

import com.intest.dao.entity.PartsBigPackageBto;
import com.intest.dao.entity.PartsBigPackageBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsBigPackageBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    long countByExample(PartsBigPackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int deleteByExample(PartsBigPackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int deleteByPrimaryKey(String partsbigpackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int insert(PartsBigPackageBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int insertSelective(PartsBigPackageBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    List<PartsBigPackageBto> selectByExample(PartsBigPackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    PartsBigPackageBto selectByPrimaryKey(String partsbigpackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") PartsBigPackageBto record, @Param("example") PartsBigPackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int updateByExample(@Param("record") PartsBigPackageBto record, @Param("example") PartsBigPackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int updateByPrimaryKeySelective(PartsBigPackageBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSBIGPACKAGE
     *
     * @mbg.generated Thu Aug 27 17:05:43 CST 2020
     */
    int updateByPrimaryKey(PartsBigPackageBto record);
}