package com.intest.dao.mapper;

import com.intest.dao.entity.PartsUpgradePackageBto;
import com.intest.dao.entity.PartsUpgradePackageBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsUpgradePackageBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    long countByExample(PartsUpgradePackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int deleteByExample(PartsUpgradePackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int deleteByPrimaryKey(String partsupgradepackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int insert(PartsUpgradePackageBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int insertSelective(PartsUpgradePackageBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    List<PartsUpgradePackageBto> selectByExample(PartsUpgradePackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    PartsUpgradePackageBto selectByPrimaryKey(String partsupgradepackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") PartsUpgradePackageBto record, @Param("example") PartsUpgradePackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByExample(@Param("record") PartsUpgradePackageBto record, @Param("example") PartsUpgradePackageBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByPrimaryKeySelective(PartsUpgradePackageBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSUPGRADEPACKAGE
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByPrimaryKey(PartsUpgradePackageBto record);
}