package com.intest.dao.mapper;

import com.intest.dao.entity.PartsTypeBto;
import com.intest.dao.entity.PartsTypeBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsTypeBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    long countByExample(PartsTypeBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int deleteByExample(PartsTypeBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int deleteByPrimaryKey(String partstypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int insert(PartsTypeBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int insertSelective(PartsTypeBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    List<PartsTypeBto> selectByExample(PartsTypeBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    PartsTypeBto selectByPrimaryKey(String partstypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") PartsTypeBto record, @Param("example") PartsTypeBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByExample(@Param("record") PartsTypeBto record, @Param("example") PartsTypeBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByPrimaryKeySelective(PartsTypeBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_PARTSTYPE
     *
     * @mbg.generated Fri Aug 21 13:55:17 CST 2020
     */
    int updateByPrimaryKey(PartsTypeBto record);
}