package com.intest.dao.mapper;

import com.intest.dao.entity.TableColumnBto;
import com.intest.dao.entity.TableColumnBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TableColumnBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    long countByExample(TableColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByExample(TableColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int deleteByPrimaryKey(String tablecolumnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insert(TableColumnBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int insertSelective(TableColumnBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    List<TableColumnBto> selectByExample(TableColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    TableColumnBto selectByPrimaryKey(String tablecolumnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") TableColumnBto record, @Param("example") TableColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByExample(@Param("record") TableColumnBto record, @Param("example") TableColumnBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKeySelective(TableColumnBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_TABLECOLUMN
     *
     * @mbg.generated Wed Aug 12 10:43:19 CST 2020
     */
    int updateByPrimaryKey(TableColumnBto record);
}