package com.intest.dao.mapper;

import com.intest.dao.entity.UpgradePackageFileinfoBto;
import com.intest.dao.entity.UpgradePackageFileinfoBtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpgradePackageFileinfoBtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    long countByExample(UpgradePackageFileinfoBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int deleteByExample(UpgradePackageFileinfoBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int deleteByPrimaryKey(String upgradepackagefileinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int insert(UpgradePackageFileinfoBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int insertSelective(UpgradePackageFileinfoBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    List<UpgradePackageFileinfoBto> selectByExample(UpgradePackageFileinfoBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    UpgradePackageFileinfoBto selectByPrimaryKey(String upgradepackagefileinfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") UpgradePackageFileinfoBto record, @Param("example") UpgradePackageFileinfoBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByExample(@Param("record") UpgradePackageFileinfoBto record, @Param("example") UpgradePackageFileinfoBtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByPrimaryKeySelective(UpgradePackageFileinfoBto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table F_UPGRADEPACKAGEFILEINFO
     *
     * @mbg.generated Thu Sep 03 14:49:42 CST 2020
     */
    int updateByPrimaryKey(UpgradePackageFileinfoBto record);
}