server:
  port: 61042
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 20971520

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.79:1521/ney
    driver-class-name: oracle.jdbc.OracleDriver
    username: ZT_FOTA
    password: intest
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    platform: oracle
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 获取连接等待超时时间
      maxWait: 60000
      # 设置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache,并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters,去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectionProperties属性来打开mergeSql功能；打开sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      ## Email - start
  mail:
    host: smtp.qq.com
    username: 2478683913@qq.com
    password: bgepgqovjtmpdifg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ## Email - end
    #redis配置
redis:
  # Redis服务器地址
  host: 10.10.20.61
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password:
  # 连接超时时间（毫秒）
  timeout: 10000
  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
#Mybatis
mybatis:
  #加载mybatis主要配置类
  config-location: classpath:/mybatis-config.xml
  #加载mapper配置类
  mapper-locations: classpath:/mapper/*.xml

# pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#swagger2 开关
swagger2:
  enable: true

#basic-service 文件上传存储目录
upload-file.path-string: /tmp/webhost/uploadFile

## Logging配置 start
logback:
  logdir: /tmp/webhost/webApiLog
  appname: webApi
## Logging配置 end

## product配置 - start
info:
  app.name: fota-zt-web
  company.name: intest
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
## product配置 - end

## 其它配置 - start
config:
  # JWT认证加密私钥(Base64加密)
  encrypt-jwtKey: U0JBUElOENhspJrzkyNjQ1NA
  # AccessToken过期时间(秒)
  accessToken-expireTime: 12000
  # RefreshToken过期时间(秒)
  refreshToken-expireTime: 36000
  # Shiro缓存过期时间(秒)(一般设置与AccessToken过期时间一致) 此处CustomCache读取失败，待解决
  shiro-cache-expireTime: 12000
## 其它配置 - end

## shiro - start
shiro:
  annotations.enabled: false
## shiro - end

