server:
  port: 9901
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.79:1521/ney
    driver-class-name: oracle.jdbc.OracleDriver
    username: ZT_FOTA
    password: intest
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    platform: oracle
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 获取连接等待超时时间
      maxWait: 60000
      # 设置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache,并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters,去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectionProperties属性来打开mergeSql功能；打开sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#Mybatis
mybatis:
  #加载mybatis主要配置类
  config-location: classpath:/mybatis-config.xml
  #加载mapper配置类
  mapper-locations: classpath:/mapper/*.xml

#swagger2 开关
swagger2:
  enable: true

#basic-service 文件上传存储目录
upload-file.path-string: d:/tmp/webhost/uploadFile/